
/* Generated By functionGenerator v0.1
function testFunc2(input){
    if(
        (Object.prototype.toString.call(input) === "[object Number]" || Object.prototype.toString.call(input) === "[object Undefined]")
    ){

    }else{
        console.log('%cType Error : testFunc2(<Number>)','color:#00FF66;')
    }
}
*/